version: "3.8"
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite3_db:/var/lib/sqlite3/data
  fastapi:
    build: .
    # имя контейнера
    container_name: fastapiapp
    # перезапускать контейнер при завершении выполнения работы или при аварийном завершении
    restart: always
    # проброс портов внутрь контейнера, 8000 порт на хост машине будет проброшен внутрь контейнера на такой же 8000 порт
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env
    # команда при старте контейнера
    #command: >
    #  sh -c "uvicorn main:app --reload"
    volumes:
      - sqlite3_db:/usr/src/app/data
    depends_on:
      - sqlite3
    expose:
      - 8000
    networks:
      - myNetwork
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./redis.conf:/redis.conf
    networks:
      - myNetwork
    command: [ "redis-server", "/redis.conf" ]
networks:
  myNetwork:
    driver: bridge
volumes:
  sqlite3_db: